# Server Configuration
server:
  port: 8081
  servlet:
    context-path: /api/v1/

# Spring Configuration
spring:
  application:
    name: ms-bill
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/parcial-realm
        registration:
          keycloak:
            client-id: ms-partial-client
            client-secret: kDYGM9e0mpPsdQRlyMSg6tDQ92cJl9UO
            redirect-uri: http://localhost:8081/login/oauth2/code/keycloak

  # Database
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  # JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false

  # H2
  h2:
    console:
      enabled: true
      path: /h2-console

# Eureka
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#keycloak
keycloak:
  jwkset:
    url: http://localhost:8080/realms/parcial-realm/protocol/openid-connect/certs