eureka:
  instance:
    hostname: localhost
    prefer-ip-address: 'true'
  client:
    register-with-eureka: 'true'
    fetch-registry: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      routes[0]:
        id: ms-bill
        predicates: Path=/api/v1/**
        uri: lb://ms-bill
      default-filters[0]: TokenRelay
  security:
    oauth2:
      client:
        registration:
          api-gateway-service:
            authorization-grant-type: authorization_code
            provider: api-gateway-service
            scope: openid
            client-id: partial-client
            redirect-uri: http://localhost:8090/login/oauth2/code/keycloak
            client-secret: AFi9zLoZcO4dritIX7LGCbcT9cBYAaM3
        provider:
          api-gateway-service:
            issuer-uri: http://localhost:8080/realms/parcial-realm
  application:
    name: ms-gateway
server:
  port: '8090'
